day01_防抖节流
Evildoer98/daily_learning pull request #8
Opened 2021-11-15 14:50 UTC by LaicZhang

# time: 

**What kind of change does this PR introduce?** (check at least one)

- [] notes: Notes
- [ ] codes: Codes
- [ ] leetcode: LeetCode
- [ ] demo: Demo
- [ ] feature: Feature

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [] No

If yes, please describe the impact and migration path for existing codes:

**Describe the change introduced by this PR:**

**Content:**
- [ ] todo1

**Related links**
- [ ] Design from figma: 
- [ ] Document from notion: 

**Other information:**

2021-11-15 15:04 UTC, Evildoer98 requested changes

2021-11-15 15:04 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +        if (now >= delay + last) {
这里传入的 delay 是什么类型的数据？
并且last不清晰

2021-11-15 15:04 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +            last = now;
将时间类型赋值给last后，在上面判定语句中会出现类型错误。
缺少类型转换

2021-11-15 15:04 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +                    func.apply(this, arguments);
这个this指向什么？箭头函数没有this

2021-11-15 15:04 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +        clearTimeout(timeout);
一来就清除定时器，前面定义的时候都没有给值呀

2021-11-15 15:04 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +    }
你这个定时器是不是有点问题

2021-11-16 04:42 UTC, Evildoer98 requested changes

2021-11-16 04:42 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +            last = now;
你可以写一个时间转换的勾子函数，时间和number类型能进行加减哦

2021-11-16 04:42 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +            let context = this;
```suggestion
            let context = this;
            let _this = this
```

2021-11-16 04:42 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +                    func.apply(context, arguments);
```suggestion
                    func.apply(context, arguments);
                    func.apply(_this, ...arguments)
```

2021-11-16 04:42 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +        let context = this;
```suggestion
        let context = this;
        let _this = this
```

2021-11-16 04:42 UTC, Evildoer98 commented on day_01-防抖节流/防抖节流.md
> +            func.apply(context, arguments);
```suggestion
            func.apply(context, arguments);
            func.apply(_this, ...arguments)
```

2021-11-16 09:44 UTC, LaicZhang commented on day_01-防抖节流/防抖节流.md
> +            let context = this;
Data.now()返回的就是number类型的啊

2021-11-16 12:46 UTC, Evildoer98 approved these changes

2021-11-19 16:50 UTC, merged